### ISSUE TITLE
Error when generating report

### ISSUE THREAD

**Issue by TruscaPetre** [TruscaPetre/ChatGPT-edge-extension-tracker#6]
When you press the button for generating a report, nothing happens and in the Developer Console, you get the following message:

```
Error handling response: TypeError: activityLog is not iterable
    at aggregateReportData (chrome-extension://kmijkbnpmbmeflnlphnbdfdonkgliccf/content.js:77:43)
    at createReportElement (chrome-extension://kmijkbnpmbmeflnlphnbdfdonkgliccf/content.js:53:22)
    at chrome-extension://kmijkbnpmbmeflnlphnbdfdonkgliccf/content.js:39:20
```

**Comment by TruscaPetre** [comment]
This has been fixed, the issue was on the case where were no messages in the activityLog, we are now issuing an alert in that case
